@echo off
echo Starting App...
cd /d "%~dp0"

echo Checking dependencies...
if not exist node_modules (
    echo Installing dependencies. This may take a minute...
    call npm install
)

echo Starting development server...
call npm run dev
